MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG_CNN_M_1024.add_VGG_CNN_M_1024_conv5_body
  NUM_CLASSES: 6
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 60000
  STEPS: [0, 30000, 40000]
  # Equivalent schedules with...
  # 1 GPU:
  #   BASE_LR: 0.0025
  #   MAX_ITER: 60000
  #   STEPS: [0, 30000, 40000]
  # 2 GPUs:
  #   BASE_LR: 0.005
  #   MAX_ITER: 30000
  #   STEPS: [0, 15000, 20000]
  # 4 GPUs:
  #   BASE_LR: 0.01
  #   MAX_ITER: 15000
  #   STEPS: [0, 7500, 10000]
  # 8 GPUs:
  #   BASE_LR: 0.02
  #   MAX_ITER: 7500
  #   STEPS: [0, 3750, 5000]
FAST_RCNN:
  ROI_BOX_HEAD: VGG_CNN_M_1024.add_VGG_CNN_M_1024_roi_fc_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: ../pretrained/vgg16_CNN_M_1024.pkl
  DATASETS: ('mobilityaids_RGB_train',)
  SCALES: (540,)
  MAX_SIZE: 960
  BATCH_SIZE_PER_IM: 256
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  USE_FLIPPED: False
  ASPECT_GROUPING: False
  SNAPSHOT_ITERS: 5000
TEST:
  FORCE_JSON_DATASET_EVAL: True
  DATASETS: ('mobilityaids_RGB_test',
             'mobilityaids_RGB_test2_seq1',
             'mobilityaids_RGB_test2_seq2',
             'mobilityaids_RGB_test2_seq3',
             'mobilityaids_RGB_test2_seq4')
  SCALE: 540
  MAX_SIZE: 960
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: mobilityaids_models/VGG-M/
